# Generated by Django 2.2.2 on 2019-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.IntegerField()),
                ('EmpSal', models.IntegerField()),
                ('EmpAdd', models.CharField(max_length=30)),
            ],
        ),
    ]
