# Generated by Django 2.2.7 on 2020-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='EmpName',
            field=models.CharField(max_length=30),
        ),
    ]
